### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by zbraniecki** [Berrysoft/language-matcher#1]
In the README it states:
> And, if you have noticed, the language matching data in the JSON data of CLDR is broken.

Can you provide more context?

**Comment by Berrysoft** [comment]
The `languageMatching.json` records the supported language only but no desired one. For example, the line in `languageInfo.xml`
``` xml
<languageMatch desired="nb"	supported="no"	distance="1"/>	<!-- nb ⇒ no -->
```
and the same part in ths JSON data
``` json
{
  "no": {
    "_distance": "1"
  }
},
```
I've found a [fixed JSON one](https://github.com/Squarespace/cldr/blob/master/compiler/src/main/resources/fixes/languageMatching-fix.json) by others, but didn't use it because the XML one is OK.

**Comment by zbraniecki** [comment]
Thank you for explaining!

@srl295 - is that an intentional divergence?

**Comment by srl295** [comment]
> Thank you for explaining!
> 
> @srl295 - is that an intentional divergence?

doesn't look intentional, please file a ticket
